export const allCards = [
  { id: "card-1", img: "benin-bronze.jpg" },
  { id: "card-2", img: "igbo-ukwu.jpg" },
  { id: "card-3", img: "terracota.jpg" },
  { id: "card-4", img: "arubar.jpg" },
  { id: "card-5", img: "benin-bronze-2.jpg" },
  { id: "card-6", img: "benin-sculptures.jpg" },
  { id: "card-7", img: "durbar.jpg" },
  { id: "card-8", img: "eyo.jpg" },
  { id: "card-9", img: "terracota-2.jpg" },
  { id: "card-10", img: "Olusegun-Obasanjo.jpg" },
  { id: "card-11", img: "azikiwe.jpg" },
  { id: "card-12", img: "benson-idahosa.jpg" },
  { id: "card-13", img: "Goodluck-Jonathan.jpeg" },
  { id: "card-14", img: "ngozi.jpg" },
  { id: "card-15", img: "Peter-obi.jpg" },
  { id: "card-16", img: "obafemi-awolowo.jpg" },
  { id: "card-17", img: "card-9.jpg" },
  { id: "card-18", img: "coat-of-arms.jpg" },
  { id: "card-19", img: "flag.jpg" },
  { id: "card-20", img: "card-8.jpg" },
  { id: "card-21", img: "card-7.jpg" },
  { id: "card-22", img: "card-6.jpg" },
];
