interface LevelType {
  id: number;
  name: string;
  totalCards: number;
  pairs: number;
  cols: number;
  rows: number;
  w: string;
  h: string;
  time: number;
  duplicates: 2 | 4 | 6;
  reveaDuration: number;
}

export const levels: LevelType[] = [
  {
    id: 1,
    name: "Beginner",
    totalCards: 6,
    pairs: 3,
    cols: 3,
    rows: 2,
    w: "max-w-[150px]",
    h: "h-full",
    time: 25,
    duplicates: 2,
    reveaDuration: 2000,
  },
  {
    id: 2,
    name: "Novice",
    totalCards: 8,
    pairs: 4,
    cols: 4,
    rows: 2,
    w: "max-w-[140px]",
    h: "h-full",
    time: 35,
    duplicates: 2,
    reveaDuration: 2000,
  },
  {
    id: 3,
    name: "Easy",
    totalCards: 12,
    pairs: 6,
    cols: 4,
    rows: 3,
    w: "max-w-[130px]",
    h: "h-40",
    time: 50,
    duplicates: 2,
    reveaDuration: 2000,
  },
  {
    id: 4,
    name: "Medium",
    totalCards: 16,
    pairs: 8,
    cols: 4,
    rows: 4,
    w: "max-w-[80px]",
    h: "h-full",
    time: 60,
    duplicates: 2,
    reveaDuration: 2000,
  },
  {
    id: 5,
    name: "Challenging",
    totalCards: 20,
    pairs: 10,
    cols: 5,
    rows: 4,
    w: "max-w-[80px]",
    h: "h-full",
    time: 70,
    duplicates: 2,
    reveaDuration: 2500,
  },
  {
    id: 6,
    name: "Hard",
    totalCards: 24,
    pairs: 12,
    cols: 6,
    rows: 4,
    w: "max-w-[80px]",
    h: "h-full",
    time: 80,
    duplicates: 2,
    reveaDuration: 3000,
  },
  {
    id: 7,
    name: "Expert",
    totalCards: 32,
    pairs: 8,
    cols: 8,
    rows: 4,
    w: "max-w-[80px]",
    h: "h-full",
    time: 90,
    duplicates: 4,
    reveaDuration: 3000,
  },
  {
    id: 8,
    name: "Master",
    totalCards: 36,
    pairs: 9,
    cols: 9,
    rows: 4,
    w: "max-w-[80px]",
    h: "h-full",
    time: 100,
    duplicates: 4,
    reveaDuration: 3500,
  },
  {
    id: 9,
    name: "Legend",
    totalCards: 40,
    pairs: 10,
    cols: 10,
    rows: 4,
    w: "max-w-[80px]",
    h: "h-full",
    time: 120,
    duplicates: 4,
    reveaDuration: 4000,
  },
  {
    id: 10,
    name: "Dominator",
    totalCards: 48,
    pairs: 12,
    cols: 12,
    rows: 4,
    w: "max-w-[80px]",
    h: "h-full",
    time: 150,
    duplicates: 4,
    reveaDuration: 4000,
  },
  {
    id: 11,
    name: "God Mode",
    totalCards: 52,
    pairs: 13,
    cols: 10,
    rows: 4,
    w: "max-w-[80px]",
    h: "h-full",
    time: 160,
    duplicates: 4,
    reveaDuration: 4500,
  },
];
